# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zOX731TwWQVODaNt4bwdGCoTNEK9ah_6
"""

__version__ = '0.0.1'